name: Java CI with Maven in Linux
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - java: 8
          additional-maven-args: "-Pjacoco -DrepoToken=$COVERALLS_REPO_TOKEN coveralls:report"
        - java: 11
    name: Build with Java ${{ matrix.java }} on ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK  ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: > 
         mvn -f com.examples.myproject/pom.xml 
         clean verify ${{ matrix.additional-maven-args }}
         surefire-report:report-only site:site -DgenerateReports=false
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      if: ${{ always() }}
    - name: ArchiveJUnitReport 
      uses: actions/upload-artifact@v2 
      if: ${{ always() }}
      with:
        name: surefire-report-jdk-${{ matrix.java }} 
        path: '**/target/site'
    - name: ArchiveJacocoSite
      uses: actions/upload-artifact@v2 
      if: ${{ always() }}
      with:
        name: Jacoc-Report-jdk-${{ matrix.java }} 
        path: '**/target/site/jacoco'
      